name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Install Clang 17
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17
        sudo apt-get update
        sudo apt-get install -y clang-17 lldb-17 lld-17
        clang-17 --version # Verify the installed version
    - name: install_deps
      run: |
        sudo apt-get update
        sudo apt-get -y install cproto
    - name: Check Clang Version
      run: clang++ --version
    - name: make
      run: make CC=clang-17 CXX=clang++-17

    - name: Archive production artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: Traveling_salesman_problem
        path: ./traveling_salesman_problem_Linux_x86_64

    - name: Set up date for tag
      id: date
      run: echo "DATE=$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.DATE }}
        release_name: Release-${{ env.DATE }}
        draft: false
        prerelease: false


    - name: Upload Release Asset
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./traveling_salesman_problem_Linux_x86_64
        asset_name: Traveling_salesman_problem
        asset_content_type: application/octet-stream
